PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>
PREFIX hmas: <https://purl.org/hmas/>
PREFIX td: <https://www.w3.org/2019/wot/td#>
PREFIX wotsec: <https://www.w3.org/2019/wot/security#>
PREFIX htv: <http://www.w3.org/2011/http#>
PREFIX hctl: <https://www.w3.org/2019/wot/hypermedia#>
PREFIX js: <https://www.w3.org/2019/wot/json-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT {
    GRAPH <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-sandra#>
    {
        ?farm hmas:contains ?section1.
        ?farm hmas:contains ?section2.
        ?farm hmas:contains ?section3.
        ?farm hmas:contains ?section4.

        ?section1 a td:Thing, was:LandSection;
  			td:title "Land section 1 of farm";
        .
        ?section2 a td:Thing, was:LandSection;
  			td:title "Land section 2 of farm";
        .
        ?section3 a td:Thing, was:LandSection;
  			td:title "Land section 3 of farm";
        .
        ?section4 a td:Thing, was:LandSection;
  			td:title "Land section 4 of farm";
        .
    }.
} WHERE {
	?farm a was:Farm.
  	BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-sandra#section1")) AS ?section1)
    BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-sandra#section2")) AS ?section2)
    BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-sandra#section3")) AS ?section3)
    BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-sandra#section4")) AS ?section4)
}